-
  name:  'Replicator Service'
  uriPattern: 'neos-replicator/<ServiceSubRoutes>'
  defaults:
    '@package':    'Flownative.Neos.Replicator'
    '@action':     'index'
  subRoutes:
    'ServiceSubRoutes':
      package: 'Flownative.Neos.Replicator'
      suffix:  'Service'
