#
# See Settings.yaml.example for a longer, documented example setup (and read the fine manual).
#
Flownative:
  Neos:
    Replicator:
      # a key used to authenticate against the replication API, make it long and random
      apiKey: ''

      # any number of nodes available for replication
      nodes: []

      # any number of replication configurations
      replications: []

TYPO3:
  Flow:
    mvc:
      routes:
        'Flownative.Neos.Replicator': true
    security:
      authentication:
        providers:
          AdminInterfaceProvider:
            provider: 'Flownative\Neos\Replicator\Security\ApiKeyProvider'
            providerOptions:
              authenticateRoles: ['TYPO3.Neos:Administrator', 'Flownative.Neos.Replicator:Writer']
